apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200 # 도커로 내부 공유이기 때문에 localhost나 ip로 안적어도 됨.
    uid: tempo
    isDefault: true
    editable: true
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: 'tempo'
      search:
        hide: false
      nodeGraph:
        enabled: true
      spanBar:
        type: 'Tag'
      tracesToLogs:
        datasourceUid: 'tempo'